### ISSUE TITLE
XLC series thermocouple dataloggers

### ISSUE THREAD

**Issue by BenKingsbury** [LukeVassallo/tc_logger_apps#2]
Hi Luke,
I am using one of your dataloggers, which I am very happy with by the way. I would like to know if you have any documentation for sending configuration to the device (TC type etc.) as a string using serial. I am reading data fine using python and would like to send the configuration using python, as I don't have any knowledge of C. It looks like TLOGA/B are formats for sending strings, is this correct?
Thanks,
Ben

**Comment by LukeVassallo** [comment]
Hi Ben, I am glad to hear that you're happy with the device. I don't have documentation for the configuration strings but I can put together a document over the next days. 

You are correct that TLOGA/B are different formats for sending the data. Moreover, all the fields in GUI configure the device using strings over the serial port.

Is there a way I can reach you over email to pass on the document?

Thanks,
Luke

**Comment by BenKingsbury** [comment]
Hi Luke, many thanks for your quick response. If you could put something together it would be very helpful and appreciated. My email is ben.kingsbury@outlook.com
Thanks,
Ben
